package common;

import mvc.model.IDocumentPrinter;
/**
 * Simple implementation of the <code>IDocumentPrinter</code> interface.
 * @author Tomas
 *
 */
public class SimplePrinter implements IDocumentPrinter {

	@Override
	public String printDocument(Document doc) {
		//Just return the string generated by the document's toString method
		return doc.toString();
	}
}
