package imageanalysis.hough;

import java.util.Vector;

/**
 * Class storing data generated by the Hough Transform 
 * @author Tomas Toss 26 maj 2011
 */
public class HoughData {

	private final Vector<HoughLine> lines;
	private final Vector<Intersection> intersections;

	public HoughData(final Vector<HoughLine> lines, final Vector<Intersection> intersections) {
		this.lines = lines;
		this.intersections = intersections;
	}
	
	public Vector<Intersection> getIntersections() {
		return intersections;
	}
	
	public Vector<HoughLine> getLines() {
		return lines;
	}

}
